// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybtorcsfaiopfzydjqaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidG9yY3NmYWlvcGZ6eWRqcWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5ODQwMTIsImV4cCI6MjA1MjU2MDAxMn0.GKbSewziTv-WG8E0kLHWC0La1NJRR39UsHprQ7uDZ6U"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);